site_name: SmallD
theme:
  name: readthedocs

dev_addr: 0.0.0.0:8000

nav:
  - Overview: index.md
  - "Getting Started": getting_started.md
  - Javadoc: https://www.javadoc.io/doc/com.github.princesslana/smalld
  - GitHub: https://github.com/princesslana/smalld
