build: &build
  steps:
  - checkout
  - run: |
      echo 'export SMALLD_VERSION="$(git describe --dirty --tags)-SNAPSHOT"' >> $BASH_ENV
      echo 'export MAVEN_OPTS="-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"' >> $BASH_ENV
  - restore_cache:
      key: smalld-{{ checksum "pom.xml" }}
  - run: mvn -B verify

version: 2
jobs:
  dependency_cache:
    docker:
      - image: maven:3-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: smalld-{{ checksum "pom.xml" }}
      - run: mvn -B dependency:go-offline
      - save_cache:
          paths:
          - ~/.m2
          key: smalld-{{ checksum "pom.xml" }}
  java8:
    <<: *build
    docker:
      - image: maven:3-jdk-8
    persist_to_workspace:
      root: .
  java11:
    <<: *build
    docker:
      - image: maven:3-jdk-11
  corretto8:
    <<: *build
    docker:
      - image: maven:3-amazoncorretto-8
  sonarcloud:
    docker:
      - image: maven:3-jdk-8
    steps:
      - attach_workspace:
          at: .


workflows:
  version: 2
  verify:
    jobs:
      - dependency_cache
      - java8:
          requires:
            - dependency_cache
      - java11:
          requires:
            - dependency_cache
      - corretto8:
          requires:
            - dependency_cache
