build: &build
  steps:
  - checkout
  - run: mvn -B verify

version: 2
jobs:
  java8:
    <<: *build
    docker:
      - image: maven:3-jdk-8
  java11:
    <<: *build
    docker:
      - image: maven:3-jdk-11

workflows:
  version: 2
  verify:
    jobs:
      - java8
      - java11
