version: 2
jobs:
  verify:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: mvn -B verify

workflows:
  version: 2
  verify:
    jobs:
      - verify:
          image: mvn:3-jdk-8
      - verify:
          image: mvn:3-jdk-11
          
