build: &build
  steps:
  - checkout
  - run: |
      echo 'export SMALLD_VERSION="$(git describe --dirty --tags)-SNAPSHOT"' >> $BASH_ENV
      echo 'export MAVEN_OPTS="-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"' >> $BASH_ENV
  - restore_cache:
      key: smalld-{{ checksum "pom.xml" }}
  - run: mvn -B dependency:go-offline
  - save_cache:
      paths:
      - ~/.m2
      key: smalld-{{ checksum "pom.xml" }}
  - run: mvn -B verify

version: 2
jobs:
  java8:
    <<: *build
    docker:
      - image: maven:3-jdk-8
  java11:
    <<: *build
    docker:
      - image: maven:3-jdk-11
  corretto8:
    <<: *build
    docker:
      - image: maven:3-amazoncorretto-8

workflows:
  version: 2
  verify:
    jobs:
      - java8
      - java11
      - corretto8
