version: 2
jobs:
  java8:
    docker:
      - image: maven:3-jdk-8
    steps:
      - checkout
      - run: mvn -B verify
  java11:
    docker:
      - image: maven:3-jdk-11
    steps:
      - checkout
      - run: mvn -B verify
